# my global config
# Author: MageEdu <mage@magedu.com>
# Repo: http://gitlab.magedu.com/MageEdu/prometheus-configs/
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
    scheme: http

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - 'record.rules'
  - 'alert.rules'
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
    - targets:
      - localhost:9090

  # All nodes
  - job_name: 'nodes'
    consul_sd_configs:
    - server: "consul:8500"
      tags:
      - "nodes"
      refresh_interval: 2m 

  # grafana
  - job_name: 'grafana'
    consul_sd_configs:
    - server: "consul:8500"
      tags:
      - "grafana"
      refresh_interval: 2m 

  # consul-exporter
  - job_name: 'consul-exporter'
    consul_sd_configs:
    - server: "consul:8500"
      tags:
      - "consul-exporter"
      refresh_interval: 2m 

  # mysqld-exporter
  - job_name: 'mysqld-exporter'
    consul_sd_configs:
    - server: "consul:8500"
      tags:
      - "mysqld-exporter"
      refresh_interval: 2m 

  # nginx-exporter
  - job_name: 'nginx-exporter'
    consul_sd_configs:
    - server: "consul:8500"
      tags:
      - "nginx-exporter"
      refresh_interval: 2m 


  # tomcat
  - job_name: 'tomcat'
    consul_sd_configs:
    - server: "consul:8500"
      tags:
      - "tomcat"
      refresh_interval: 2m 

  # Blackbox Exporter
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    file_sd_configs:
    - files:
      - targets/sites-*.yaml
      refresh_interval: 2m
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "blackbox_exporter:9115"  # Blackbox exporter.
      - target_label: region
        replacement: "local"
